# Generated by Django 2.2.3 on 2019-07-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the domain you want to receive email for.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"db_table": "domains"},
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="The email address of the mail account.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="The hashed password of the mail account. It is prepended by the hashing algorithm. By default it is {SHA256-CRYPT} encrypted. But you may have legacy users that still use {PLAIN-MD5}. Adding the hashing algorithm allows you to have different kinds of hashes.",
                        max_length=150,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to="core.Domain",
                    ),
                ),
            ],
            options={"verbose_name_plural": "mailboxes", "db_table": "mailboxes"},
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="The email address that the email was actually sent to.",
                        max_length=100,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="The email address that the email should instead be sent to.",
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.Domain",
                    ),
                ),
            ],
            options={"verbose_name_plural": "aliases", "db_table": "alias"},
        ),
    ]
