# Generated by Django 2.2.3 on 2019-08-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="quota",
            field=models.IntegerField(
                default=0, help_text="Quota limit in kilobytes, 0 means unlimited."
            ),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="quota_suffix",
            field=models.CharField(
                blank=True,
                choices=[("M", "MiB"), ("G", "GiB"), ("T", "TiB")],
                help_text="If suffix is set, it changes quota units.",
                max_length=1,
            ),
        ),
    ]
